import type { Recipe } from "./types";

export const RECIPES: Recipe[] = [
  {
    id: "r001",
    emoji: "🥗",
    name: { en: "Quinoa Power Bowl", ko: "퀴노아 파워볼" },
    description: {
      en: "Protein-packed quinoa bowl with roasted vegetables and tahini dressing",
      ko: "구운 채소와 타히니 드레싱을 곁들인 고단백 퀴노아 볼",
    },
    mealType: ["lunch", "dinner"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 30,
    servings: 2,
    nutrition: {
      calories: 480,
      protein: 18,
      carbs: 62,
      fat: 18,
      fiber: 9,
      vitaminB12: 0,
      iron: 4.5,
      calcium: 120,
      omega3: 0.3,
      zinc: 3.2,
    },
    ingredients: {
      en: ["Quinoa", "Sweet potato", "Chickpeas", "Kale", "Tahini", "Lemon"],
      ko: ["퀴노아", "고구마", "병아리콩", "케일", "타히니", "레몬"],
    },
    tags: ["high-protein", "high-fiber", "meal-prep"],
  },
  {
    id: "r002",
    emoji: "🥞",
    name: { en: "Oat Banana Pancakes", ko: "오트 바나나 팬케이크" },
    description: {
      en: "Fluffy plant-based pancakes with oats and ripe banana",
      ko: "귀리와 잘 익은 바나나로 만든 폭신한 팬케이크",
    },
    mealType: ["breakfast"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 15,
    servings: 2,
    nutrition: {
      calories: 320,
      protein: 10,
      carbs: 58,
      fat: 6,
      fiber: 5,
      vitaminB12: 0,
      iron: 2.5,
      calcium: 60,
      omega3: 0.1,
      zinc: 1.8,
    },
    ingredients: {
      en: ["Oats", "Banana", "Plant milk", "Cinnamon", "Maple syrup"],
      ko: ["귀리", "바나나", "식물성 우유", "시나몬", "메이플 시럽"],
    },
    tags: ["quick", "kid-friendly"],
  },
  {
    id: "r003",
    emoji: "🍛",
    name: { en: "Lentil Curry", ko: "렌틸 커리" },
    description: {
      en: "Rich and creamy lentil curry with coconut milk and warming spices",
      ko: "코코넛 밀크와 향신료로 풍미를 낸 크리미한 렌틸 커리",
    },
    mealType: ["lunch", "dinner"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 40,
    servings: 4,
    nutrition: {
      calories: 420,
      protein: 22,
      carbs: 55,
      fat: 12,
      fiber: 15,
      vitaminB12: 0,
      iron: 6.5,
      calcium: 80,
      omega3: 0.2,
      zinc: 3.8,
    },
    ingredients: {
      en: [
        "Red lentils",
        "Coconut milk",
        "Onion",
        "Garlic",
        "Turmeric",
        "Cumin",
        "Rice",
      ],
      ko: ["붉은 렌틸콩", "코코넛 밀크", "양파", "마늘", "강황", "커민", "밥"],
    },
    tags: ["high-protein", "high-iron", "comfort-food"],
  },
  {
    id: "r004",
    emoji: "🥑",
    name: { en: "Avocado Toast Deluxe", ko: "아보카도 토스트 디럭스" },
    description: {
      en: "Loaded avocado toast with cherry tomatoes, microgreens and seeds",
      ko: "방울토마토, 새싹채소, 씨앗을 올린 풍성한 아보카도 토스트",
    },
    mealType: ["breakfast", "snack"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 10,
    servings: 1,
    nutrition: {
      calories: 350,
      protein: 9,
      carbs: 30,
      fat: 22,
      fiber: 8,
      vitaminB12: 0,
      iron: 2.0,
      calcium: 40,
      omega3: 0.5,
      zinc: 1.5,
    },
    ingredients: {
      en: [
        "Whole grain bread",
        "Avocado",
        "Cherry tomatoes",
        "Hemp seeds",
        "Lemon",
      ],
      ko: ["통곡물 빵", "아보카도", "방울토마토", "헴프씨드", "레몬"],
    },
    tags: ["quick", "omega-3"],
  },
  {
    id: "r005",
    emoji: "🍝",
    name: { en: "Creamy Mushroom Pasta", ko: "크리미 버섯 파스타" },
    description: {
      en: "Silky cashew cream pasta with sauteed mushrooms and fresh herbs",
      ko: "캐슈 크림과 볶은 버섯, 신선한 허브의 실키한 파스타",
    },
    mealType: ["lunch", "dinner"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 25,
    servings: 2,
    nutrition: {
      calories: 520,
      protein: 15,
      carbs: 68,
      fat: 20,
      fiber: 4,
      vitaminB12: 0,
      iron: 3.0,
      calcium: 50,
      omega3: 0.1,
      zinc: 2.5,
    },
    ingredients: {
      en: [
        "Pasta",
        "Cashews",
        "Mushrooms",
        "Garlic",
        "Nutritional yeast",
        "Thyme",
      ],
      ko: ["파스타", "캐슈넛", "버섯", "마늘", "뉴트리셔널 이스트", "타임"],
    },
    tags: ["comfort-food", "b12-source"],
  },
  {
    id: "r006",
    emoji: "🧆",
    name: { en: "Falafel Wrap", ko: "팔라펠 랩" },
    description: {
      en: "Crispy baked falafel in a warm wrap with hummus and pickled veggies",
      ko: "허무스와 피클 채소를 넣은 바삭한 오븐 구이 팔라펠 랩",
    },
    mealType: ["lunch"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 35,
    servings: 2,
    nutrition: {
      calories: 450,
      protein: 16,
      carbs: 52,
      fat: 20,
      fiber: 10,
      vitaminB12: 0,
      iron: 4.0,
      calcium: 100,
      omega3: 0.2,
      zinc: 2.8,
    },
    ingredients: {
      en: [
        "Chickpeas",
        "Parsley",
        "Cumin",
        "Wrap tortilla",
        "Hummus",
        "Cucumber",
      ],
      ko: ["병아리콩", "파슬리", "커민", "토르티야", "허무스", "오이"],
    },
    tags: ["high-fiber", "high-iron", "meal-prep"],
  },
  {
    id: "r007",
    emoji: "🥣",
    name: { en: "Overnight Chia Pudding", ko: "오버나이트 치아 푸딩" },
    description: {
      en: "Creamy chia seed pudding with mixed berries and granola",
      ko: "베리와 그래놀라를 올린 크리미한 치아씨드 푸딩",
    },
    mealType: ["breakfast", "snack"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 5,
    servings: 1,
    nutrition: {
      calories: 280,
      protein: 8,
      carbs: 35,
      fat: 12,
      fiber: 11,
      vitaminB12: 0,
      iron: 2.0,
      calcium: 250,
      omega3: 2.5,
      zinc: 1.5,
    },
    ingredients: {
      en: [
        "Chia seeds",
        "Almond milk",
        "Mixed berries",
        "Granola",
        "Maple syrup",
      ],
      ko: ["치아씨드", "아몬드 밀크", "믹스 베리", "그래놀라", "메이플 시럽"],
    },
    tags: ["omega-3", "calcium", "no-cook"],
  },
  {
    id: "r008",
    emoji: "🍲",
    name: { en: "Tofu Stir-Fry", ko: "두부 볶음" },
    description: {
      en: "Crispy tofu with colorful vegetables in a savory soy-ginger sauce",
      ko: "간장 생강 소스에 다채로운 채소와 바삭한 두부 볶음",
    },
    mealType: ["lunch", "dinner"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 20,
    servings: 2,
    nutrition: {
      calories: 380,
      protein: 24,
      carbs: 30,
      fat: 18,
      fiber: 5,
      vitaminB12: 0,
      iron: 5.0,
      calcium: 350,
      omega3: 0.4,
      zinc: 2.5,
    },
    ingredients: {
      en: [
        "Firm tofu",
        "Broccoli",
        "Bell pepper",
        "Soy sauce",
        "Ginger",
        "Sesame oil",
      ],
      ko: ["두부", "브로콜리", "파프리카", "간장", "생강", "참기름"],
    },
    tags: ["high-protein", "high-calcium", "quick"],
  },
  {
    id: "r009",
    emoji: "🌶️",
    name: { en: "Sweet Potato & Black Bean Chili", ko: "고구마 블랙빈 칠리" },
    description: {
      en: "Hearty and spicy chili packed with sweet potatoes and black beans",
      ko: "고구마와 블랙빈이 듬뿍 들어간 든든하고 매콤한 칠리",
    },
    mealType: ["lunch", "dinner"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 45,
    servings: 4,
    nutrition: {
      calories: 390,
      protein: 15,
      carbs: 65,
      fat: 6,
      fiber: 14,
      vitaminB12: 0,
      iron: 4.5,
      calcium: 90,
      omega3: 0.1,
      zinc: 2.2,
    },
    ingredients: {
      en: [
        "Sweet potato",
        "Black beans",
        "Tomatoes",
        "Onion",
        "Chili powder",
        "Cumin",
      ],
      ko: ["고구마", "블랙빈", "토마토", "양파", "칠리 파우더", "커민"],
    },
    tags: ["high-fiber", "meal-prep", "comfort-food"],
  },
  {
    id: "r010",
    emoji: "🥙",
    name: { en: "Mediterranean Buddha Bowl", ko: "지중해식 부다볼" },
    description: {
      en: "Colorful bowl with hummus, roasted vegetables, olives and feta",
      ko: "허무스, 구운 채소, 올리브, 페타 치즈의 다채로운 볼",
    },
    mealType: ["lunch", "dinner"],
    vegetarianType: ["lacto-ovo", "lacto"],
    prepTime: 30,
    servings: 2,
    nutrition: {
      calories: 460,
      protein: 14,
      carbs: 48,
      fat: 24,
      fiber: 10,
      vitaminB12: 0.5,
      iron: 3.5,
      calcium: 180,
      omega3: 0.3,
      zinc: 2.0,
    },
    ingredients: {
      en: [
        "Couscous",
        "Hummus",
        "Feta cheese",
        "Olives",
        "Roasted zucchini",
        "Cherry tomatoes",
      ],
      ko: [
        "쿠스쿠스",
        "허무스",
        "페타 치즈",
        "올리브",
        "구운 호박",
        "방울토마토",
      ],
    },
    tags: ["calcium", "mediterranean"],
  },
  {
    id: "r011",
    emoji: "🍜",
    name: { en: "Miso Ramen Bowl", ko: "미소 라멘 볼" },
    description: {
      en: "Warming miso broth with noodles, tofu, mushrooms and greens",
      ko: "두부, 버섯, 푸른 채소를 넣은 따뜻한 미소 라멘",
    },
    mealType: ["lunch", "dinner"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 25,
    servings: 2,
    nutrition: {
      calories: 410,
      protein: 18,
      carbs: 55,
      fat: 14,
      fiber: 6,
      vitaminB12: 0,
      iron: 4.0,
      calcium: 150,
      omega3: 0.3,
      zinc: 2.2,
    },
    ingredients: {
      en: [
        "Miso paste",
        "Ramen noodles",
        "Silken tofu",
        "Shiitake mushrooms",
        "Bok choy",
        "Nori",
      ],
      ko: ["미소된장", "라멘 면", "순두부", "표고버섯", "청경채", "김"],
    },
    tags: ["comfort-food", "iron-source"],
  },
  {
    id: "r012",
    emoji: "🥜",
    name: { en: "Peanut Butter Energy Bites", ko: "피넛버터 에너지볼" },
    description: {
      en: "No-bake protein balls with oats, peanut butter and dark chocolate",
      ko: "귀리, 땅콩버터, 다크 초콜릿으로 만든 노오븐 프로틴 볼",
    },
    mealType: ["snack"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 10,
    servings: 4,
    nutrition: {
      calories: 180,
      protein: 7,
      carbs: 20,
      fat: 9,
      fiber: 3,
      vitaminB12: 0,
      iron: 1.5,
      calcium: 30,
      omega3: 0.1,
      zinc: 1.0,
    },
    ingredients: {
      en: [
        "Peanut butter",
        "Oats",
        "Dark chocolate chips",
        "Flaxseed",
        "Agave",
      ],
      ko: ["땅콩버터", "귀리", "다크 초콜릿 칩", "아마씨", "아가베"],
    },
    tags: ["quick", "no-cook", "protein-snack"],
  },
  {
    id: "r013",
    emoji: "🥦",
    name: { en: "Broccoli Cheddar Soup", ko: "브로콜리 체다 수프" },
    description: {
      en: "Creamy broccoli soup with melted cheddar and crusty bread",
      ko: "녹인 체다 치즈와 바삭한 빵을 곁들인 크리미 브로콜리 수프",
    },
    mealType: ["lunch", "dinner"],
    vegetarianType: ["lacto-ovo", "lacto"],
    prepTime: 30,
    servings: 3,
    nutrition: {
      calories: 310,
      protein: 14,
      carbs: 28,
      fat: 16,
      fiber: 5,
      vitaminB12: 0.8,
      iron: 2.0,
      calcium: 320,
      omega3: 0.1,
      zinc: 2.0,
    },
    ingredients: {
      en: [
        "Broccoli",
        "Cheddar cheese",
        "Onion",
        "Vegetable broth",
        "Cream",
        "Bread",
      ],
      ko: ["브로콜리", "체다 치즈", "양파", "채소 육수", "크림", "빵"],
    },
    tags: ["calcium", "b12-source", "comfort-food"],
  },
  {
    id: "r014",
    emoji: "🌮",
    name: { en: "Jackfruit Tacos", ko: "잭프루트 타코" },
    description: {
      en: "Pulled jackfruit tacos with slaw, avocado and lime crema",
      ko: "슬로, 아보카도, 라임 크레마를 곁들인 잭프루트 타코",
    },
    mealType: ["lunch", "dinner"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 30,
    servings: 3,
    nutrition: {
      calories: 380,
      protein: 8,
      carbs: 52,
      fat: 16,
      fiber: 7,
      vitaminB12: 0,
      iron: 2.5,
      calcium: 60,
      omega3: 0.3,
      zinc: 1.2,
    },
    ingredients: {
      en: [
        "Jackfruit",
        "Taco shells",
        "Cabbage",
        "Avocado",
        "Lime",
        "Chipotle",
      ],
      ko: ["잭프루트", "타코 쉘", "양배추", "아보카도", "라임", "치폴레"],
    },
    tags: ["creative", "fiber"],
  },
  {
    id: "r015",
    emoji: "🍳",
    name: { en: "Spinach & Feta Omelette", ko: "시금치 페타 오믈렛" },
    description: {
      en: "Fluffy omelette filled with spinach, feta cheese and sun-dried tomatoes",
      ko: "시금치, 페타 치즈, 건조 토마토를 넣은 폭신한 오믈렛",
    },
    mealType: ["breakfast"],
    vegetarianType: ["lacto-ovo", "ovo"],
    prepTime: 10,
    servings: 1,
    nutrition: {
      calories: 340,
      protein: 22,
      carbs: 8,
      fat: 24,
      fiber: 2,
      vitaminB12: 1.5,
      iron: 3.5,
      calcium: 250,
      omega3: 0.2,
      zinc: 2.5,
    },
    ingredients: {
      en: ["Eggs", "Spinach", "Feta cheese", "Sun-dried tomatoes", "Olive oil"],
      ko: ["달걀", "시금치", "페타 치즈", "건조 토마토", "올리브 오일"],
    },
    tags: ["high-protein", "b12-source", "calcium", "quick"],
  },
  {
    id: "r016",
    emoji: "🍌",
    name: { en: "Green Smoothie Bowl", ko: "그린 스무디볼" },
    description: {
      en: "Vibrant green smoothie bowl topped with fruits, nuts and seeds",
      ko: "과일, 견과류, 씨앗을 올린 생기 넘치는 그린 스무디볼",
    },
    mealType: ["breakfast", "snack"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 5,
    servings: 1,
    nutrition: {
      calories: 310,
      protein: 8,
      carbs: 52,
      fat: 10,
      fiber: 7,
      vitaminB12: 0,
      iron: 3.0,
      calcium: 100,
      omega3: 1.0,
      zinc: 1.5,
    },
    ingredients: {
      en: [
        "Spinach",
        "Banana",
        "Mango",
        "Almond butter",
        "Hemp seeds",
        "Coconut flakes",
      ],
      ko: [
        "시금치",
        "바나나",
        "망고",
        "아몬드 버터",
        "헴프씨드",
        "코코넛 플레이크",
      ],
    },
    tags: ["quick", "iron-source", "omega-3"],
  },
  {
    id: "r017",
    emoji: "🍕",
    name: { en: "Veggie Flatbread Pizza", ko: "채소 플랫브레드 피자" },
    description: {
      en: "Crispy flatbread topped with pesto, roasted vegetables and mozzarella",
      ko: "페스토, 구운 채소, 모짜렐라를 올린 바삭한 플랫브레드 피자",
    },
    mealType: ["lunch", "dinner"],
    vegetarianType: ["lacto-ovo", "lacto"],
    prepTime: 20,
    servings: 2,
    nutrition: {
      calories: 440,
      protein: 16,
      carbs: 48,
      fat: 20,
      fiber: 4,
      vitaminB12: 0.5,
      iron: 2.5,
      calcium: 220,
      omega3: 0.1,
      zinc: 2.0,
    },
    ingredients: {
      en: [
        "Flatbread",
        "Pesto",
        "Mozzarella",
        "Roasted peppers",
        "Artichoke",
        "Arugula",
      ],
      ko: [
        "플랫브레드",
        "페스토",
        "모짜렐라",
        "구운 파프리카",
        "아티초크",
        "루꼴라",
      ],
    },
    tags: ["calcium", "kid-friendly"],
  },
  {
    id: "r018",
    emoji: "🥤",
    name: { en: "B12 Fortified Smoothie", ko: "B12 강화 스무디" },
    description: {
      en: "Nutritional yeast smoothie with berries, banana and fortified plant milk",
      ko: "뉴트리셔널 이스트, 베리, 바나나, 강화 식물성 우유 스무디",
    },
    mealType: ["breakfast", "snack"],
    vegetarianType: ["vegan", "lacto-ovo", "lacto", "ovo"],
    prepTime: 5,
    servings: 1,
    nutrition: {
      calories: 240,
      protein: 10,
      carbs: 42,
      fat: 4,
      fiber: 5,
      vitaminB12: 2.5,
      iron: 1.5,
      calcium: 300,
      omega3: 0.5,
      zinc: 2.0,
    },
    ingredients: {
      en: [
        "Fortified plant milk",
        "Nutritional yeast",
        "Banana",
        "Mixed berries",
        "Flaxseed",
      ],
      ko: [
        "강화 식물성 우유",
        "뉴트리셔널 이스트",
        "바나나",
        "믹스 베리",
        "아마씨",
      ],
    },
    tags: ["b12-source", "calcium", "quick", "omega-3"],
  },
];
